<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <xacro:macro name="link_azimuth_thruster" params="originxyx_ parent_">
        <joint name="thruster_sb_joint" type="revolute">
            <origin xyz="originxyx_" rpy="0 0 0"/>
            <parent link="parent_"/>
            <child link="thruster_sb_link"/>
            <axis xyz="0 0 1"/>
            <limit lower="${-pi*0.75}" upper="${pi*0.75}" velocity="2.0" effort="10"/> 
        </joint>
    </xacro:macro>  

    <xacro:macro name="joint_azimuth_thruster" params="name_">
        <link name="name_">
            <visual>
                <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
                <geometry>                
                    <cylinder length="${arm_length}" radius="${arm_radius}" />
                </geometry>
                <material name="orange" />
            </visual>
            <collision>
                <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
                <geometry>
                    <cylinder length="${arm_length}" radius="${arm_radius}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
                <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>  


    <!-- Specify some standard inertial calculations https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
    <!-- These make use of xacro's mathematical functionality -->

    <xacro:macro name="inertial_sphere" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                    izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>  


    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>


</robot>